# docker-compose.yml
version: '3.8'

services:
  # redis:
  #   image: redis:7-alpine
  #   container_name: lottery-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes

  app:
    build: .
    container_name: lottery_server
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WECHAT_APPID=${WECHAT_APPID}
      - WECHAT_SECRET=${WECHAT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    # depends_on:
    #   - redis
    env_file:
      - .env

  nginx:
    image: gmerit/lottery-app
    container_name: lottery_app
    restart: unless-stopped
    ports:
      - '80:9100'
    # volumes:
    #   - ./nginx/conf.d:/etc/nginx/conf.d
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 可选自定义主配置
    #   - certbot_data:/etc/letsencrypt
    #   - certbot_www:/var/www/certbot
    depends_on:
      - lottery_server

  # certbot:
  #   image: certbot/certbot
  #   container_name: lottery-certbot
  #   restart: unless-stopped
  #   volumes:
  #     - certbot_data:/etc/letsencrypt
  #     - certbot_www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --dry-run; sleep 12h; done;'"
# volumes:
#   redis_data:
#   certbot_data:
#   certbot_www:
